---
title: "GARFO Exploration"
author: "cslovas"
format: 
  html:
    toc: true
    self-contained: true
editor: visual
---

```{r}
#| label: read in clean (ish) GARFO data
#| echo: false
#| message: false

library(tidyverse)
library(gmRi)
library(here)
library(grid)

garfo_clean    <- read.csv(here("Data", "all_GARFO_data.csv"))
garfo_landings <- read.csv(here("Data", "landings.csv"))
# garfo_geo <- read.csv(here("Data", "cleaned_geocodes.csv"))

```

# Summaries

## Totals by state


```{r}
#| label: summary stats by state 
#| echo: false
#| message: false
#| fig-align: center
#| fig-height: 6
#| fig-width: 9

garfo_clean %>%
  pivot_longer(cols = BLACK_SEA_BASS_1:TILEFISH_D, names_to = "PERMIT_TYPE", values_to = "COUNT") %>%
  select(PPORT, PPST, AP_NUM, AP_YEAR, VP_NUM, PERMIT_TYPE, COUNT) %>%
  filter(PPST %in% c("ME", "NH", "MA", "RI", "CT", "DE", "MD", "VA", "NC")) %>%
  filter(!is.na(COUNT)) %>%
  filter(!COUNT == 0) -> garfo_holdings

# unique(garfo_holdings$PERMIT_TYPE)

garfo_holdings %>%
  arrange(PPST) %>%
  group_by(PPST, AP_YEAR) %>%
  summarise(TOTAL_COUNT = sum(COUNT)) %>%
  ggplot() +
  geom_col(aes(x = AP_YEAR, y = TOTAL_COUNT), fill = "#00608A") +
  facet_wrap(~PPST, scales = "free_y")  +
  xlab("Year") + ylab("Total Licenses Issued") + ggtitle("Number of licenses issued annually by state") +
  theme_gmri(strip.background = element_rect(fill = "transparent"),
             strip.text = element_text(color = "black")) 

```
```{r}
#| label: landings
#| echo: false
#| message: false
#| warning: false
#| fig-align: center
#| fig-height: 6
#| fig-width: 9 
#| 
garfo_landings %>%
  filter(YEAR >= 1990 & STATE %in% c("ME", "NH", "MA", "CT", "RI", "DE", "MD", "VA", "NC")) %>% 
  mutate(LANDED.LBS = parse_number(LANDED.LBS)) %>%
  group_by(YEAR, STATE) %>% 
  summarise(TOTAL.LANDED = sum(LANDED.LBS, na.rm = TRUE)) %>%
  mutate(TOTAL.LANDED = TOTAL.LANDED/1000000) %>%
  arrange(STATE) %>% 
  ggplot() +
  geom_col(aes(x = YEAR, y = TOTAL.LANDED), fill = "#00608A") +
  facet_wrap(~STATE, scales = "free_y")  +
  xlab("Year") + ylab("Total Landed Pounds (millions)") + ggtitle("Annual landings by state") +
  theme_gmri(strip.background = element_rect(fill = "transparent"),
             strip.text = element_text(color = "black"))


```

### Maine

```{r}
#| label: ME
#| echo: false 
#| message: false
#| fig-align: center
#| fig-width: 10
#| fig-height: 8

garfo_holdings %>%
  arrange(PPST) %>%
  filter(PPST == "ME") %>%
  group_by(PPST, AP_YEAR, PERMIT_TYPE) %>%
  summarise(TOTAL_COUNT = sum(COUNT)) %>%
  group_by(PPST, PERMIT_TYPE) %>% 
  ggplot()+
  geom_col(aes(x = AP_YEAR, y = TOTAL_COUNT, fill = PERMIT_TYPE), position = "stack") +
  xlab("Year") + ylab("Total Licenses Issued") +
  theme_gmri(legend.position = "bottom") +
  guides(fill = guide_legend(ncol = 6)) +
  scale_fill_gmri()
```

### New Hampshire

```{r}
#| label: NH
#| echo: false 
#| message: false
#| fig-align: center
#| fig-width: 10
#| fig-height: 8

garfo_holdings %>%
  arrange(PPST) %>%
  filter(PPST == "NH") %>%
  group_by(PPST, AP_YEAR, PERMIT_TYPE) %>%
  summarise(TOTAL_COUNT = sum(COUNT)) %>%
  group_by(PPST, PERMIT_TYPE) %>% 
  ggplot()+
  geom_col(aes(x = AP_YEAR, y = TOTAL_COUNT, fill = PERMIT_TYPE), position = "stack") +
  xlab("Year") + ylab("Total Licenses Issued") +
  theme_gmri(legend.position = "bottom") +
  guides(fill = guide_legend(ncol = 6)) +
  scale_fill_gmri()
```

### Massachusetts

```{r}
#| label: MA
#| echo: false 
#| message: false
#| fig-align: center
#| fig-width: 10
#| fig-height: 8

garfo_holdings %>%
  arrange(PPST) %>%
  filter(PPST == "MA") %>%
  group_by(PPST, AP_YEAR, PERMIT_TYPE) %>%
  summarise(TOTAL_COUNT = sum(COUNT)) %>%
  group_by(PPST, PERMIT_TYPE) %>% 
  ggplot()+
  geom_col(aes(x = AP_YEAR, y = TOTAL_COUNT, fill = PERMIT_TYPE), position = "stack") +
  xlab("Year") + ylab("Total Licenses Issued") +
  theme_gmri(legend.position = "bottom") +
  guides(fill = guide_legend(ncol = 6)) +
  scale_fill_gmri()
```

### Connecticut

```{r}
#| label: CT
#| echo: false 
#| message: false
#| fig-align: center
#| fig-width: 10
#| fig-height: 8

garfo_holdings %>%
  arrange(PPST) %>%
  filter(PPST == "CT") %>%
  group_by(PPST, AP_YEAR, PERMIT_TYPE) %>%
  summarise(TOTAL_COUNT = sum(COUNT)) %>%
  group_by(PPST, PERMIT_TYPE) %>% 
  ggplot()+
  geom_col(aes(x = AP_YEAR, y = TOTAL_COUNT, fill = PERMIT_TYPE), position = "stack") +
  xlab("Year") + ylab("Total Licenses Issued") +
  theme_gmri(legend.position = "bottom") +
  guides(fill = guide_legend(ncol = 6)) +
  scale_fill_gmri()
```

### Rhode Island

```{r}
#| label: RI
#| echo: false 
#| message: false
#| fig-align: center
#| fig-width: 10
#| fig-height: 8

garfo_holdings %>%
  arrange(PPST) %>%
  filter(PPST == "RI") %>%
  group_by(PPST, AP_YEAR, PERMIT_TYPE) %>%
  summarise(TOTAL_COUNT = sum(COUNT)) %>%
  group_by(PPST, PERMIT_TYPE) %>% 
  ggplot()+
  geom_col(aes(x = AP_YEAR, y = TOTAL_COUNT, fill = PERMIT_TYPE), position = "stack") +
  xlab("Year") + ylab("Total Licenses Issued") +
  theme_gmri(legend.position = "bottom") +
  guides(fill = guide_legend(ncol = 6)) +
  scale_fill_gmri()
```

### Delaware

```{r}
#| label: DE
#| echo: false 
#| message: false
#| fig-align: center
#| fig-width: 10
#| fig-height: 8

garfo_holdings %>%
  arrange(PPST) %>%
  filter(PPST == "DE") %>%
  group_by(PPST, AP_YEAR, PERMIT_TYPE) %>%
  summarise(TOTAL_COUNT = sum(COUNT)) %>%
  group_by(PPST, PERMIT_TYPE) %>% 
  ggplot()+
  geom_col(aes(x = AP_YEAR, y = TOTAL_COUNT, fill = PERMIT_TYPE), position = "stack") +
  xlab("Year") + ylab("Total Licenses Issued") +
  theme_gmri(legend.position = "bottom") +
  guides(fill = guide_legend(ncol = 6)) +
  scale_fill_gmri()
```

### Maryland

```{r}
#| label: MD
#| echo: false 
#| message: false
#| fig-align: center
#| fig-width: 10
#| fig-height: 8

garfo_holdings %>%
  arrange(PPST) %>%
  filter(PPST == "MD") %>%
  group_by(PPST, AP_YEAR, PERMIT_TYPE) %>%
  summarise(TOTAL_COUNT = sum(COUNT)) %>%
  group_by(PPST, PERMIT_TYPE) %>% 
  ggplot()+
  geom_col(aes(x = AP_YEAR, y = TOTAL_COUNT, fill = PERMIT_TYPE), position = "stack") +
  xlab("Year") + ylab("Total Licenses Issued") +
  theme_gmri(legend.position = "bottom") +
  guides(fill = guide_legend(ncol = 6)) +
  scale_fill_gmri()
```

### Virginia

```{r}
#| label: VA
#| echo: false 
#| message: false
#| fig-align: center
#| fig-width: 10
#| fig-height: 8

garfo_holdings %>%
  arrange(PPST) %>%
  filter(PPST == "VA") %>%
  group_by(PPST, AP_YEAR, PERMIT_TYPE) %>%
  summarise(TOTAL_COUNT = sum(COUNT)) %>%
  group_by(PPST, PERMIT_TYPE) %>% 
  ggplot()+
  geom_col(aes(x = AP_YEAR, y = TOTAL_COUNT, fill = PERMIT_TYPE), position = "stack") +
  xlab("Year") + ylab("Total Licenses Issued") +
  theme_gmri(legend.position = "bottom") +
  guides(fill = guide_legend(ncol = 6)) +
  scale_fill_gmri()
```

### North Carolina

```{r}
#| label: NC
#| echo: false 
#| message: false
#| fig-align: center
#| fig-width: 10
#| fig-height: 8

garfo_holdings %>%
  arrange(PPST) %>%
  filter(PPST == "NC") %>%
  group_by(PPST, AP_YEAR, PERMIT_TYPE) %>%
  summarise(TOTAL_COUNT = sum(COUNT)) %>%
  group_by(PPST, PERMIT_TYPE) %>% 
  ggplot()+
  geom_col(aes(x = AP_YEAR, y = TOTAL_COUNT, fill = PERMIT_TYPE), position = "stack") +
  xlab("Year") + ylab("Total Licenses Issued") +
  theme_gmri(legend.position = "bottom") +
  guides(fill = guide_legend(ncol = 6)) +
  scale_fill_gmri()
```

# Unique license types per year

```{r}
#| label: license types
#| echo: false
#| message: false
#| fig-align: center
#| fig-height: 6
#| fig-width: 9

garfo_holdings %>% 
  ungroup() %>%
  select(AP_YEAR, PERMIT_TYPE) %>% 
  distinct() %>%
  group_by(AP_YEAR) %>% 
  nest() %>% 
  mutate(UNIQUE = map_dbl(data, function(x){nrow(x)})) %>%
  ggplot() +
  geom_line(aes(x = AP_YEAR, y = UNIQUE)) +
  xlab("Year") + ylab("Number of licenses types issued per year") +
  theme_gmri(strip.background = element_rect(fill = "transparent"),
             strip.text = element_text(color = "black"))

```

# Averages

## Average number of licenses per vessel over time

```{r}
#| label: license per vessel
#| echo: false
#| message: false
#| fig-align: center
#| fig-height: 6
#| fig-width: 9

garfo_holdings %>% 
  group_by(PPST, VP_NUM, AP_YEAR) %>% 
  summarise(TOTAL_COUNT = sum(COUNT)) %>% 
  group_by(PPST, AP_YEAR) %>% 
  summarise(AVG_NUM_LICENSES = mean(TOTAL_COUNT)) %>% 
  ggplot() +
  geom_line(aes(x = AP_YEAR, y = AVG_NUM_LICENSES)) +
  facet_wrap(~PPST) +
  xlab("Year") + ylab("Number of licenses per vessel") +
  theme_gmri(strip.background = element_rect(fill = "transparent"),
             strip.text = element_text(color = "black"))

```

## Average number of vessels registered in each state over time

```{r}
#| label: vessels by state
#| echo: false
#| message: false
#| fig-align: center
#| fig-height: 6
#| fig-width: 9

garfo_holdings %>%
  ungroup() %>% 
  select(PPST, AP_YEAR, VP_NUM) %>% 
  distinct() %>% 
  group_by(PPST, AP_YEAR) %>% 
  nest() %>% 
  mutate(VESSELS = map_dbl(data, function(x){nrow(x)})) %>% 
  arrange(PPST) %>% 
  ggplot() +
  geom_col(aes(x = AP_YEAR, y = VESSELS), fill = "#00608A") +
  facet_wrap(~PPST, scales = "free_y") + 
  xlab("Year") + ylab("Number of registered vessels") +
  theme_gmri(strip.background = element_rect(fill = "transparent"),
             strip.text = element_text(color = "black"))
    

```

```{r}
#| label: landings vs licenses by port
#| echo: false

# garfo_landings %>% 
#   filter(YEAR >= 1996) %>% 
#   rename("PPORT"   = "PORT.NAME",
#          "PPST"    = "STATE",
#          "AP_YEAR" = "YEAR") %>% 
#   mutate(LANDED.LBS = parse_number(LANDED.LBS))%>% 
#   group_by(AP_YEAR, PPORT, PPST) %>% 
#   summarise(TOTAL_LBS = sum(LANDED.LBS)) -> landings_by_port
# 
# garfo_holdings %>% 
#   group_by(AP_YEAR, PPORT, PPST) %>% 
#   summarise(TOTAL_LICENSES = sum(COUNT)) %>% 
#   right_join(landings_by_port) %>% 
#   unite(PPORT, PPST, col = "PORT", sep = ", ") -> landings_with_licenses
#   
# unique(landings_with_licenses$PORT)

## this is probably not the way to do this

```