---
title: "Figure development"
subtitle: "What happens when an important coastal fishery collapses in a rural state"
author: "cslovas"
format: 
  html:
    toc: true
    self-contained: true
editor: visual
---

Consolidating outputs from various different scripts to compile different iterations of figures intended for objective 1 paper

```{r}
#| label: data dependencies
#| echo: false
#| message: false
#| warning: false

library(tidyverse)
library(readr)
library(gmRi)
library(here)

# All license types
## species portfolio
license_portfolio      <- read_rds(here("Data","clean_portfolio.rds"))
## time series (count)
license_time_series    <- read_rds(here("Data","license_time_series.rds"))
## annual_metrics
license_metrics_series <- read_rds(here("Data","license_metrics_series.rds"))

# Target species
## species_portfolio 
species_portfolio <- read_rds(here("Data","species_level_portfolio.rds"))
## time series (count)
species_time_series <- read_rds(here("Data","species_time_series.rds"))
## annual_metrics
species_metrics_series <- read_rds(here("Data","species_metrics_series.rds"))

# Stoll et all [revised] divisions

## species portfolio
stoll_portfolio      <- read_rds(here("Data","stoll_portfolio.rds"))
## time series (count)
stoll_time_series    <- read_rds(here("Data","stoll_time_series.rds"))
## annual_metrics
stoll_metrics_series <- read_rds(here("Data","stoll_metrics_series.rds"))


## license codes and categories for ordering
license_codes <- read.csv(here("Data", "updated_license_codes.csv")) %>%
  rename("license_type" = "code") %>% 
  mutate(description = str_to_sentence(description))

license_divisions <- read.csv(here("Data", "LicenseSubdivision_list.csv")) %>%
  # select(License.Type, Target.Species, Stoll.et.al..2016.Name) %>%
  rename("description" = "License.Type",
         "group" = "Target.Species",
         "license_group" = "Stoll.et.al.2016.Name",
         "divisions" = "Stoll.et.al.2016")

license_divisions %>% 
  left_join(license_codes %>% select(!group)) -> licenses
```

## Constrained hierarchical clustering

```{r}
#| label: clustering
#| echo: false
#| warning: false
#| message: false
#| fig-width: 7
#| fig-height: 5

library(dendextend)
library(rioja) #chclust()
library(vegan) #bstick()
library(factoextra) #fviz_dist()

years     <- 1990:2025
#################
# All License Types
license_portfolio %>% 
  ungroup() %>%
  select(!landings_number) %>%
  pivot_longer(cols = 2:50, names_to = "category", values_to = "count") %>% 
  filter(!count == 0) %>% 
  group_by(license_year, category) %>% 
  summarise(count = sum(count)) %>% 
  pivot_wider(names_from = "category", values_from = "count") %>% 
  arrange(license_year) %>% 
  select(!license_year) -> dend

## distance
eucdist<-vegdist(as.matrix(dend),method="euclidean",binary=FALSE,diag=FALSE,upper=FALSE,na.rm=TRUE)

## clustering
cl<-chclust(eucdist,method="coniss")

as.dendrogram(cl) %>%
  set("labels", years) %>%
  set("labels_col", value = c("#07a3b7", "#ea4f12", "#767676"), k=3) %>%
  set("branches_k_color",value = c("#07a3b7", "#ea4f12", "#767676"), k=3) %>%
  plot(main = "All license types", xlab = "Year", ylab = "Sum of squares")

#################
# Species level
species_portfolio %>% 
  ungroup() %>%
  select(!landings_number) %>%
  pivot_longer(cols = 2:20, names_to = "category", values_to = "count") %>% 
  filter(!count == 0) %>% 
  group_by(license_year, category) %>% 
  summarise(count = sum(count)) %>% 
  pivot_wider(names_from = "category", values_from = "count") %>% 
  arrange(license_year) %>% 
  select(!license_year) -> dend

## distance
eucdist<-vegdist(as.matrix(dend),method="euclidean",binary=FALSE,diag=FALSE,upper=FALSE,na.rm=TRUE)

## clustering
cl<-chclust(eucdist,method="coniss")

as.dendrogram(cl) %>%
  set("labels", years) %>%
  set("labels_col", value = c("#07a3b7", "#ea4f12", "#767676"), k=3) %>%
  set("branches_k_color",value = c("#07a3b7", "#ea4f12", "#767676"), k=3) %>%
  plot(main = "Species level license groupings", xlab = "Year", ylab = "Sum of squares")

#################
# Stoll divisions
stoll_portfolio %>% 
  ungroup() %>%
  select(!landings_number) %>%
  pivot_longer(cols = 2:27, names_to = "category", values_to = "count") %>% 
  filter(!count == 0) %>% 
  group_by(license_year, category) %>% 
  summarise(count = sum(count)) %>% 
  pivot_wider(names_from = "category", values_from = "count") %>% 
  arrange(license_year) %>% 
  select(!license_year) -> dend

## distance
eucdist<-vegdist(as.matrix(dend),method="euclidean",binary=FALSE,diag=FALSE,upper=FALSE,na.rm=TRUE)

## clustering
cl<-chclust(eucdist,method="coniss")

as.dendrogram(cl) %>%
  set("labels", years) %>%
  set("labels_col", value = c("#07a3b7", "#ea4f12", "#767676"), k=3) %>%
  set("branches_k_color",value = c("#07a3b7", "#ea4f12", "#767676"), k=3) %>%
  plot(main = "Stoll et al divisions [revised]", xlab = "Year", ylab = "Sum of squares")
```

## Heatmaps

```{r}
#| label: heatmaps
#| echo: false
#| warning: false
#| message: false
#| fig-width: 7
#| fig-height: 5

order <- c("Scallop (Dragger)",
           "Scallop (Tender)",
           "Scallop (Hand)",
           "Lobster Apprentice & Student", 
           "Lobster Class I",
           "Lobster Class II",
           "Lobster Class III",
           "Green crab",
           "Marine worm",
           "Shellfish",
           "Surf Clam",
           "Mussel",
           "Mahogany Clam",
           "Seaweed",
           "Sea Urchin (Dragger)",
           "Sea Urchin (Hand)",
           "Sea Urchin (Tender)",
           "Elver",
           "Eel",
           "Northern Shrimp",
           "Sea Cucumber",
           "Pelagic & Anadromous",
           "Commercial Fishing",
           "Aquaculture",
           "Spat",
           "Menhaden")
rev_order <- rev(order)

# All license types
license_time_series %>%
  left_join(licenses %>% select(description, Order_ID)) %>% 
  arrange(desc(Order_ID)) %>% 
  group_by(data) %>%
  summarise(description = factor(description)) %>%
  unnest(data) %>% 
  ggplot() +
  geom_tile(aes(x = license_year, y = factor(description), alpha = total), fill = "#00608A", color = "#FFFFFF") +
  ylab("License category") + xlab("Year") +
  ggtitle("All license types") +
  guides(alpha = guide_legend(title = "Total number issued")) +
  geom_vline(aes(xintercept = 1998), linetype = 1, color = "#07a3b7") +
  geom_vline(aes(xintercept = 2013), linetype = 1, color = "#ea4f12") +
  theme_gmri(panel.grid.major = element_blank(),
             axis.line = element_blank(),
             axis.text.y = element_text(size = 6)) 

# Species level
licenses %>% 
  select(group) %>% 
  distinct() %>% 
  rename("species" = "group") %>%
  rowid_to_column() %>% 
  arrange(desc(rowid)) %>% 
  left_join(species_time_series) %>% 
  group_by(data) %>%
  summarise(species = factor(species, levels = species)) %>%
  unnest(data) %>% 
  distinct() %>% 
  ggplot() +
  geom_tile(aes(x = license_year, y = species, alpha = count), fill = "#00608A", color = "#FFFFFF") +
  ylab("License category") + xlab("Year") +
  ggtitle("Species level grouping") +
  guides(alpha = guide_legend(title = "Total number issued")) +
  geom_vline(aes(xintercept = 1994), linetype = 1, color = "#07a3b7") +
  geom_vline(aes(xintercept = 2007), linetype = 1, color = "#ea4f12") +
  theme_gmri(panel.grid.major = element_blank(),
             axis.line = element_blank()) 

# Stoll divisions
stoll_time_series %>% 
   unnest(data) %>% 
  ggplot() +
  geom_tile(aes(x = license_year, y = factor(license_group, level = rev_order), alpha = total), fill = "#00608A", color = "#FFFFFF") +
  ylab("License category") + xlab("Year") +
  ggtitle("Stoll et al divisions [revised]") +
  guides(alpha = guide_legend(title = "Total number issued")) +
  geom_vline(aes(xintercept = 1999), linetype = 1, color = "#07a3b7") +
  geom_vline(aes(xintercept = 2011), linetype = 1, color = "#ea4f12") +
  theme_gmri(panel.grid.major = element_blank(),
             axis.line = element_blank()) 
```

## Network Metrics

### Degree centrality

Stoll divisions only

```{r}
#| label: degree centrality
#| echo: false
#| message: false
#| warning: false
#| fig-width: 11
#| fig-height: 8.5

# license_metrics_series %>% 
#   select(license_year, degree) %>% 
#   unnest_longer(degree) %>% 
#   group_by(degree_id) %>%
#   rename("license_group" = "degree_id") %>% 
#   mutate(level = "all_licenses") -> licenses_degree
# 
# species_metrics_series %>% 
#   select(license_year, degree) %>% 
#   unnest_longer(degree) %>% 
#   group_by(degree_id) %>%
#   rename("license_group" = "degree_id") %>% 
#   mutate(level = "species_level") -> species_degree

stoll_metrics_series %>% 
  select(license_year, degree) %>% 
  unnest_longer(degree) %>% 
  group_by(degree_id) %>%
  rename("license_group" = "degree_id") %>% 
  mutate(level = "stoll_divisions") -> stoll_degree

ggplot(data = stoll_degree) +
  geom_line(aes(x = license_year, y = degree)) + # color = factor(license_group, levels = order))) + 
  scale_color_gmri() +
  xlab("Year") + ylab("Degree centrality") + ggtitle("Degree centrality", subtitle = "Stoll et al license groupings; Louvain clustering") +
  theme_gmri(legend.position = "bottom", 
             plot.subtitle = element_text(size =  11),
             strip.background = element_rect(fill = "transparent"), 
             strip.text = element_text(color = "black", hjust = 0),
             panel.border = element_rect(color = "black", linetype = 1),
             panel.grid.major = element_line(color = "#e9e9e9", linetype = 1),
             panel.grid.minor = element_line(color = "#e9e9e9", linetype = 1)) +
  facet_wrap(~license_group, ncol = 4) 
  # guides(color = guide_legend(title = "License category", nrow = 4))
  

```

### Edge density and modularity

```{r}
#| label: density and modularity
#| echo: false
#| message: false
#| warning: false
#| fig-width: 7
#| fig-height: 5

license_metrics_series %>% 
  select(license_year, density, modularity) %>%
  mutate(density = as.numeric(density),
         modularity = as.numeric(modularity),
         level = "all_licenses") %>% 
  full_join(species_metrics_series %>%
              select(license_year, density, modularity) %>%
              mutate(level = "species_level")) %>% 
  full_join(stoll_metrics_series %>%
              select(license_year, density, modularity) %>%
              mutate(level = "stoll")) -> dens_mod

ggplot(data = dens_mod, aes(x = license_year, y = density, color = level)) +
  geom_line(aes(linetype = level)) +
  # geom_point(aes(shape = level)) +
  theme_gmri(axis.text  = element_text(size = 8),
                 panel.border = element_rect(color = "black", linetype = 1),
                 panel.grid.major = element_line(color = "#e9e9e9", linetype = 1),
                 panel.grid.minor = element_line(color = "#e9e9e9", linetype = 1)) +
  xlab("Year") + ylab("Edge density") + ggtitle("Edge Density") +
scale_color_manual("License groupings", labels = c("Disaggregate", "Species level", "Stoll et al."), values = c("#00608a", "#ea4f12", "#38431d")) +
  scale_linetype_discrete("License groupings", labels = c("Disaggregate", "Species level", "Stoll et al."))

ggplot(data = dens_mod, aes(x = license_year, y = modularity, color = level)) +
  geom_line(aes(linetype = level)) +
  theme_gmri(axis.text  = element_text(size = 8),
                 panel.border = element_rect(color = "black", linetype = 1),
                 panel.grid.major = element_line(color = "#e9e9e9", linetype = 1),
                 panel.grid.minor = element_line(color = "#e9e9e9", linetype = 1)) +
  xlab("Year") + ylab("Modularity") + ggtitle("Modularity") +
  scale_color_manual("License groupings", labels = c("Disaggregate", "Species level", "Stoll et al."), values = c("#00608a", "#ea4f12", "#38431d")) +
  scale_linetype_discrete("License groupings", labels = c("Disaggregate", "Species level", "Stoll et al."))

```

## Chord diagrams

#### Pre-closure

2009-2013

```{r}
#| label: preclosure
#| echo: false
#| message: false
#| warning: false

# make co-matrices
stoll_portfolio %>% 
  ungroup() %>% 
  filter(license_year %in% c(2009:2013, 2016:2020)) %>%
  select(!landings_number) %>% 
  arrange(license_year) %>%
  group_by(license_year) %>% 
  nest() %>% 
  mutate(co_matrix = map(data, function(x){
    out <- crossprod(as.matrix(x))
    diag(out) <- 0
    return(out)
  })) %>% 
  mutate(closure = ifelse(license_year <= 2013, "pre_closure", "post_closure")) -> co_matrices

pre_closure  <- (co_matrices$co_matrix[[1]] + co_matrices$co_matrix[[2]] + co_matrices$co_matrix[[3]] + co_matrices$co_matrix[[4]] + co_matrices$co_matrix[[5]])/5 # there's probably a more efficient way to do this but I'm tired...

post_closure <- (co_matrices$co_matrix[[6]] + co_matrices$co_matrix[[7]] + co_matrices$co_matrix[[8]] + co_matrices$co_matrix[[9]] + co_matrices$co_matrix[[10]])/5

# Chord diagrams
library(chorddiag)
palette <- c("#773891", "#535353", "#363b45", "#004966", "#00608a", "#07a3b7", "#057872", "#38431d", "#abb400", "#ebcb27", "#ea4f12", "#b94a40")

chorddiag(data = as.matrix(pre_closure),
          type = "directional",
          showTicks = FALSE,
          groupPadding = 5,
          groupColors = palette,
          chordedgeColor = palette,
          groupnameFontsize = 8)
```

#### Post-closure

2016-2020

```{r}
#| label: postclosure
#| echo: false
#| message: false
#| warning: false
chorddiag(data = as.matrix(post_closure),
          type = "directional",
          showTicks = FALSE,
          groupPadding = 5,
          groupColors = palette,
          chordedgeColor = palette,
          groupnameFontsize = 8)
```
