---
title: "Cleaned Network Plots"
author: "cslovas"
format: 
  html:
    toc: true
    self-contained: true
editor: visual
---

```{r}
#| label:   load libraries & data
#| echo:    false
#| message: false
#| warning: false

# Install & load the libraries
library(tidyverse)
library(tidygraph)
library(ggraph)
library(igraph)
library(here)
library(gmRi)
library(grid)
library(gt)

# Read in tidy license data
path <- here()
me_all_lics_1990_2022_tidy <- read_csv((paste0(path, "/Data/me_all_lics_1990_2022_tidy.csv")))

# Read in updated license codes 
updated_license_codes <- read.csv(here("Data", "updated_license_codes.csv")) %>%
  rename("license_type" = "code")
```

```{r}
#| label:   cleaning data
#| echo:    false
#| message: false
#| fig-height: 9

# Remove indigenous and non-harvester licenses
license_types <- names(ind_lic_portfolio %>%
                         select(!c(landings_number, license_year)))
license_types <- as_tibble(license_types) %>%
  rename("license_type" = "value") %>%
  left_join(updated_license_codes) %>%
  mutate(description = str_to_sentence(description))

license_types %>%
  filter(!group %in% c("Demo","Post-Harvest", "Non-resident", "Recreational")) %>%
  filter(!(str_starts(license_type, "ma"))) %>%
  filter(!(str_starts(license_type, "mi"))) %>%
  filter(!(str_starts(license_type, "nb"))) %>%
  filter(!(str_starts(license_type, "p")))  %>%
  filter(!license_type %in% c("st", "sts", "csw", "csws", "fhc", "mws", "mw", "nfhc", "nfhs")) %>%
  drop_na() -> license_types # the one NA here is sut 
```

```{r}
#| label: drop non-occuring years 
#| echo: false
#| message: false
#| warning: false 

me_all_lics_1990_2022_tidy %>% 
  filter(license_type %in% license_types$license_type) %>%
  filter(!license_year == "2022") %>%
  select(license_year, license_type) %>% 
  distinct() -> unique_licenses # filter matrix by this list?


```

